apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
    spec:
      containers:
      - name: log-processor
        image: gcr.io/gcp-log-processing-infra/log-processor:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: log-processor
spec:
  selector:
    app: log-processor
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP